# NumPy Exercises

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.rand()

0.5437416148808096

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
np.random.randn(25)

array([ 0.74288834, -0.96547918, -0.34971492,  0.1022217 , -0.75518753,
       -0.11600572,  0.47152921, -0.48730813,  0.41727003, -0.74260443,
       -0.46529964,  1.03517724,  0.28445155, -1.17790258,  1.07168606,
        1.11782733,  0.76406967, -0.70556461, -1.34480565,  1.17741233,
       -0.91207228,  0.09668485, -0.48236757,  0.46886907,  0.20461016])

#### Create the following matrix:

In [11]:
np.random.random_sample((10,10))

array([[0.55169061, 0.72579383, 0.23266408, 0.08801707, 0.39595519,
        0.74764647, 0.60068124, 0.82910406, 0.7034303 , 0.52603505],
       [0.10487017, 0.71707636, 0.4952124 , 0.28032382, 0.5883788 ,
        0.80029904, 0.78579625, 0.55690341, 0.99469711, 0.68191622],
       [0.98387909, 0.80449395, 0.15154265, 0.59664317, 0.71859887,
        0.33380328, 0.82588917, 0.1028791 , 0.12216094, 0.78037789],
       [0.21131965, 0.99261365, 0.12353866, 0.26806509, 0.23505979,
        0.86790833, 0.68074397, 0.21374264, 0.76336077, 0.71692127],
       [0.80260976, 0.16295225, 0.76551096, 0.50596184, 0.47886227,
        0.50492473, 0.10153167, 0.05128943, 0.63364899, 0.19541031],
       [0.33688311, 0.7442743 , 0.3278028 , 0.32972502, 0.34091752,
        0.3493001 , 0.85558138, 0.81747801, 0.16818228, 0.4258324 ],
       [0.3325944 , 0.51538257, 0.54258562, 0.10513503, 0.65816421,
        0.16403968, 0.21986928, 0.43751049, 0.11028451, 0.45102078],
       [0.33443276, 0.85778139, 0.5983407

#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Replicate the resulting matrix outputs:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [15]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [16]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [17]:
mat[3,4]

20

In [18]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [19]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [20]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [21]:
mat[4]

array([21, 22, 23, 24, 25])

In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [23]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [24]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [25]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [26]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])